"$schema" = 'https://starship.rs/config-schema.json'
# █
format = """
[╭─█](lavender)\
[](bg:blue fg:lavender)\
$os\
$username\
[](bg:blue fg:sapphire)\
[](bg:sky fg:sapphire)\
$directory\
[](bg:sky fg:teal)\
[](bg:green fg:teal)\
$git_branch\
$git_status\
[](bg:green fg:yellow)\
[](bg:peach fg:yellow)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](bg:peach fg:maroon)\
[](bg:red fg:maroon)\
$docker_context\
$conda\
[](bg:red fg:mauve)\
[](bg:pink fg:mauve)\
$time\
[](bg:pink fg:flamingo)\
[](fg:flamingo)\
$line_break\
[╰─](lavander)\
$character"""

palette = 'catppuccin_mocha'

# [palettes.gruvbox_dark]
# text = '#fbf1c7'
# green = '#3c3836'
# teal = '#665c54'
# sky = '#458588'
# sapphire = '#689d6a'
# color_green = '#98971a'
# lavender = '#d65d0e'
# color_purple = '#b16286'
# color_red = '#cc241d'
# blue = '#d79921'

[os]
disabled = false
style = "bg:blue fg:base"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Pop = ""
NixOS = ""
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:blue fg:base"
style_root = "bg:blue fg:base"
format = '[ $user]($style)'

[directory]
style = "fg:base bg:sky"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:base bg:peach)]($style)'

[c]
symbol = " "
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:base bg:peach)]($style)'

[rust]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:base bg:peach)]($style)'

[golang]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:base bg:peach)]($style)'

[php]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:base bg:peach)]($style)'

[java]
symbol = " "
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:base bg:peach)]($style)'

[kotlin]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:base bg:peach)]($style)'

[haskell]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:base bg:peach)]($style)'

[python]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:base bg:peach)]($style)'

[docker_context]
symbol = ""
style = "bg:red"
format = '[[ $symbol( $context) ](fg:#83a598 bg:red)]($style)'

[conda]
style = "bg:red"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:red)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:pink"
format = '[[ $time](fg:base bg:pink)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:mauve)'
vimcmd_replace_symbol = '[❮](bold fg:mauve)'
vimcmd_visual_symbol = '[❮](bold fg:blue)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
